import type { Metadata } from "next";
import {  Exo  } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner"
import SessionProviderWrapper from "./_components/SessionProviderWrapper/SessionProviderWrapper";
import TopBar from "./_components/TopBar/TopBar";
import { getAllCategories, getUserCart } from "@/api/services/route.services";
import { Cart } from "@/api/services/types";
import CartContextProvider from "./_providers/cartContextProvider";
const exo = Exo({
  subsets: ["latin"], 
  variable: "--font-exo",
});

// reserved name for variable
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const res = await getUserCart();
    const categories = await getAllCategories();
  return (
    <html lang="en">
      <body className={`${exo.variable} antialiased `}>
        <CartContextProvider res={res}>
          <SessionProviderWrapper>
            
            <TopBar />
            <Navbar categories={categories ?? []} />
            {children}
            <Toaster />

            <Footer />
          </SessionProviderWrapper>
        </CartContextProvider>
      </body>
    </html>
  );
}
